services:
  etlegacy:
    container_name: etlegacy
    image: sebdanielsson/etlegacy:2.80.2-6
    command: +set fs_game legacy +set fs_homepath etmain +set g_protect 1 +exec etl_server.cfg
    ports:
      - "27960:27960/udp"
    volumes:
      - ./data/etmain:/etlegacy/etmain
    restart: unless-stopped
