services:
  etlegacy:
    command: '+set fs_game legacy +set fs_homepath etmain +set g_protect 1 +exec etl_server.cfg'
    image: sebdanielsson/etlegacy:latest
    container_name: etlegacy
    ports:
      - '27960:27960/udp'
    volumes:
      - './data/etl_server.cfg:/etlegacy/etmain/etl_server.cfg'
      - './data/mapvotecycle.cfg:/etlegacy/etmain/mapvotecycle.cfg'
    restart: unless-stopped
